### ISSUE TITLE
Start using Draft pull requests for WIP translations

### ISSUE THREAD

**Issue by LucaBlackDragon** [reactjs/it.reactjs.org#119]
Hi, I've just noticed the new [Draft Pull Requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) Github feature has been enabled in this repo, so I think we should use it for translations pull requests on which we are still working (maybe together with the "work-in-progress" tag for "backwards compatibility").

In other words, the workflow would be:

1) Open a Draft Pull Request regarding a new page
2) Add its reference in the https://github.com/reactjs/it.reactjs.org/issues/1 
3) When done translating, convert the Draft Pull Request into a regular Pull Request

For an example of how this would work, please look at my new pull request (#118)

@tesseralis, @deblasis & @lssmn what do you think about it?

**Comment by deblasis** [comment]
Ciao Luca! I see your point but in terms of user experience for new contributors I prefer the issues.
They are just "plug-n-play" and people are used to them:

1. Pick the one you want by commenting that you want to work on that
2. When you are done, PR with a comment that says `Closes #id_of_the_issue`
3. 💥  **done**

One way or the other we need to pick one approach, we can't have both because otherwise surely it's gonna be cluttered 🤣 

As a side note, I'm surely going to use Draft Pull Requests for when I have to show a POC or something in other projects, instead of adding `/wait`, `/pleasedontmergethiscacca` or something. Good shout! 👍

**Comment by tesseralis** [comment]
Yeah, it's still pretty new, and I don't mind if people start using them in individual pull requests. If people get good mileage out of it I can add it as a suggestion to the issues page.
